#!/bin/bash

U_ARCHIVES_DIR=/tmp/u/packages
MISC_ARCHIVES_DIR=~/misc/packages

TMP_ROOT=/tmp/tmproot
TMP_BIN_PATH=$TMP_ROOT/bin
SETUPED_FILE=$TMP_ROOT/setuped

## Handle args
if [[ -z "$1" ]]; then
    echo "Usage: a-setup target"
    exit
fi

## Special setups
case "$1" in
    "list")
	if [[ -e $U_ARCHIVES_DIR ]]; then
	    echo "U:"
	    ls $U_ARCHIVES_DIR
	fi
	echo "MISC:"
	ls $MISC_ARCHIVES_DIR
	exit
	;;
    "u")
	a-mount-u
	exit
	;;
    "devfs")
	a-mount-devfs
	exit
	;;
esac

TARGET=$1

## Check if setuped
if [[ -e $SETUPED_FILE ]]; then
    SETUPED=$(grep -i $TARGET $SETUPED_FILE)
else
    SETUPED=""
fi
if [[ -n "$SETUPED" ]]; then
    echo "$SETUPED already setuped"
    exit
fi

## Set up source
# Try U_ARCHIVES_DIR
if [[ -e $U_ARCHIVES_DIR ]]; then
    ARCHIVE_FILE=$(ls $U_ARCHIVES_DIR | grep -i $TARGET)
    ARCHIVES_DIR=$U_ARCHIVES_DIR
fi

# Try ARCHIVES_DIR
if [[ -z "$ARCHIVE_FILE" ]]; then
    ARCHIVE_FILE=$(ls $MISC_ARCHIVES_DIR | grep -i $TARGET)
    ARCHIVES_DIR=$MISC_ARCHIVES_DIR
fi

# check
if [[ -z "$ARCHIVE_FILE" ]]; then
    echo "Can not found $TARGET"
    exit
fi
# check
AVAILABLE_COUNT=$(ls $ARCHIVES_DIR | grep -i $TARGET | wc -l)
if [[ $AVAILABLE_COUNT != "1" ]]; then
    echo There are more than one target: $ARCHIVE_FILE
    exit
fi

## Set up target
echo Setting up $ARCHIVE_FILE '(from' $ARCHIVES_DIR ')'
# make use of cache
cat $ARCHIVES_DIR/$ARCHIVE_FILE > /dev/null
tar xf $ARCHIVES_DIR/$ARCHIVE_FILE -C $TMP_ROOT && echo $ARCHIVE_FILE >> $SETUPED_FILE
